### ISSUE TITLE
Rodar um notebook pra avaliar as intents

### ISSUE THREAD

**Issue by ricardopoppi** [defensoriapublicasp/bot#24]
É necessário verificar com métodos do Rasa a qualidade das `intents` e `stories` da Dirce.

**Comment by arthurTemporim** [comment]
Notebooks atualizados e já estão na master sem problemas, para verificalos:
[intents](https://github.com/defensoriapublicasp/bot/blob/master/notebooks/intents/.ipynb_checkpoints/intents-analysis-checkpoint.ipynb)
[stories](https://github.com/defensoriapublicasp/bot/blob/master/notebooks/stories/stories-analysis.ipynb)
