### ISSUE TITLE
Pesquisar e propor o uso da API para agendamento

### ISSUE THREAD

**Issue by ricardopoppi** [defensoriapublicasp/bot#4]
**Descrição**
A partir do **CEP** ou de mais perguntas feitas pelo `chatbot`, achar a melhor localização.

**Tarefas**
- [ ] Definir como encontrar a melhor unidade para o usuário.
- [ ] Implementar funcionalidade definida

**Critérios de Aceitação**
- [ ] Usuário ser capaz de encontrar a unidade desejada.

**Comment by arthurTemporim** [comment]
O tópico de **atedimento** é refente à um subfluxo:

Neste subfluxo ele deverá encaminhar o atendimento de acordo com a cidade.

Para encaminhar o atendimento é necessário
