### ISSUE TITLE
Analisar os slides e mapear quais intents/utters/stories estão faltando pra implementação do fluxo civel/familia

### ISSUE THREAD

**Issue by ricardopoppi** [defensoriapublicasp/bot#8]
É preciso analisar os slides de modelo para que o fluxo esteja dentro do que foi definido pelo cliente.

Tarefas

- [x] Analisar e documentar fluxos faltantes

- [x] Documentar erros de fluxos existentes

- [x] Propor soluções

- [x] Documentar intents e utters faltantes

Critérios

- [x] As soluções criadas vão resolver os problemas no fluxo

- [x] O fluxo vai estar dentro do modelo indicado

**Comment by palomacmamede** [comment]
No fluxo Geral o lugar do "você pode pagar um advogado" está incorreto.
![Captura de tela de 2019-05-30 22-51-56](https://user-images.githubusercontent.com/42178586/58676210-c4cc4880-832d-11e9-96c7-f4080b476c59.png)

**Comment by palomacmamede** [comment]
Falta implementar "você recebeu uma carta", "informações do réu" e "cejusc"
![Captura de tela de 2019-05-30 23-01-07](https://user-images.githubusercontent.com/42178586/58676965-884e1c00-8330-11e9-96f3-23d568efd1bf.png)

**Comment by palomacmamede** [comment]
Falta esses dois fluxos completos: informação do réu pessoa física e informação do réu pessoa jurídica
![Captura de tela de 2019-05-30 23-40-13](https://user-images.githubusercontent.com/42178586/58678026-90a85600-8334-11e9-8662-a0a20d12d1d4.png)
![Captura de tela de 2019-05-30 23-40-16](https://user-images.githubusercontent.com/42178586/58678027-90a85600-8334-11e9-82f1-e0621c9c943f.png)

**Comment by ricardopoppi** [comment]
@arthurTemporim @gabibguedes a partir daí, precisamos corrigir e criar esses fluxos
